-- MySQL Script generated by MySQL Workbench
-- Tue Oct 31 20:54:36 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema devs_market_1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema devs_market_1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `devs_market_1` DEFAULT CHARACTER SET utf8mb4 ;
USE `devs_market_1` ;

-- -----------------------------------------------------
-- Table `devs_market_1`.`categorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `devs_market_1`.`categorias` ;

CREATE TABLE IF NOT EXISTS `devs_market_1`.`categorias` (
  `id_categoria` INT(11) NOT NULL AUTO_INCREMENT,
  `id_usuario` INT(11) NOT NULL,
  `nombreCategoria` VARCHAR(150) NULL DEFAULT NULL,
  `fechaCaptura` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `devs_market_1`.`clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `devs_market_1`.`clientes` ;

CREATE TABLE IF NOT EXISTS `devs_market_1`.`clientes` (
  `id_cliente` INT(11) NOT NULL AUTO_INCREMENT,
  `id_usuario` INT(11) NOT NULL,
  `nombre` VARCHAR(200) NULL DEFAULT NULL,
  `apellido` VARCHAR(200) NULL DEFAULT NULL,
  `direccion` VARCHAR(200) NULL DEFAULT NULL,
  `email` VARCHAR(200) NULL DEFAULT NULL,
  `telefono` VARCHAR(200) NULL DEFAULT NULL,
  `rfc` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `devs_market_1`.`imagenes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `devs_market_1`.`imagenes` ;

CREATE TABLE IF NOT EXISTS `devs_market_1`.`imagenes` (
  `id_imagen` INT(11) NOT NULL AUTO_INCREMENT,
  `id_categoria` INT(11) NOT NULL,
  `nombre` VARCHAR(500) NULL DEFAULT NULL,
  `ruta` VARCHAR(500) NULL DEFAULT NULL,
  `fechaSubida` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id_imagen`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `devs_market_1`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `devs_market_1`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `devs_market_1`.`usuarios` (
  `id_usuario` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NULL DEFAULT NULL,
  `apellido` VARCHAR(50) NULL DEFAULT NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  `direccion` VARCHAR(45) NULL DEFAULT NULL,
  `telefono` VARCHAR(15) NULL DEFAULT NULL,
  `usuario` VARCHAR(45) NULL DEFAULT NULL,
  `password` TINYTEXT NULL DEFAULT NULL,
  `fechaCaptura` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `devs_market_1`.`productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `devs_market_1`.`productos` ;

CREATE TABLE IF NOT EXISTS `devs_market_1`.`productos` (
  `id_producto` INT(11) NOT NULL AUTO_INCREMENT,
  `id_categoria` INT(11) NOT NULL,
  `id_imagen` INT(11) NOT NULL,
  `id_usuario` INT(11) NOT NULL,
  `nombre` VARCHAR(50) NULL DEFAULT NULL,
  `descripcion` VARCHAR(500) NULL DEFAULT NULL,
  `cantidad` INT(11) NULL DEFAULT NULL,
  `precio` FLOAT NULL DEFAULT NULL,
  `iva` INT(11) NULL DEFAULT NULL,
  `fechaCaptura` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id_producto`),
  INDEX `fk_productos_categorias_idx` (`id_categoria` ASC) VISIBLE,
  INDEX `fk_productos_usuarios1_idx` (`id_usuario` ASC) VISIBLE,
  INDEX `fk_productos_imagenes1_idx` (`id_imagen` ASC) VISIBLE,
  CONSTRAINT `fk_productos_categorias`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `devs_market_1`.`categorias` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productos_usuarios1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `devs_market_1`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productos_imagenes1`
    FOREIGN KEY (`id_imagen`)
    REFERENCES `devs_market_1`.`imagenes` (`id_imagen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `devs_market_1`.`ventas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `devs_market_1`.`ventas` ;

CREATE TABLE IF NOT EXISTS `devs_market_1`.`ventas` (
  `id_venta` INT(11) NOT NULL,
  `id_cliente` INT(11) NULL DEFAULT NULL,
  `id_producto` INT(11) NULL DEFAULT NULL,
  `id_usuario` INT(11) NULL DEFAULT NULL,
  `precio` FLOAT NULL DEFAULT NULL,
  `fechaCompra` DATE NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
